name: Flutter Build Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Verify the installation
      run: flutter doctor -v
      
    - name: Run analyzer
      run: flutter analyze --fatal-infos
      
    - name: Run tests
      run: flutter test --no-sound-null-safety
      
    - name: Build APK
      run: flutter build apk --release --no-sound-null-safety
      
    - name: Build iOS (no signing)
      run: flutter build ios --release --no-codesign --no-sound-null-safety